# Generated by Django 5.0 on 2024-05-14 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='supply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.supply'),
        ),
    ]
