# Generated by Django 5.0 on 2024-05-14 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When this record was updated')),
                ('donor', models.ForeignKey(help_text='Quem irá doar', on_delete=django.db.models.deletion.PROTECT, to='people.donor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When this record was updated')),
                ('beneficiary', models.ForeignKey(help_text='Quem receberá a doação', on_delete=django.db.models.deletion.PROTECT, to='people.beneficiary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonationSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When this record was updated')),
                ('quantity', models.IntegerField(help_text='Quantidade a ser recebida do item de doação')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.donation')),
                ('supply', models.ForeignKey(help_text='Item de doação a ser recebido', on_delete=django.db.models.deletion.PROTECT, to='inventory.supply')),
            ],
            options={
                'unique_together': {('donation', 'supply')},
            },
        ),
        migrations.CreateModel(
            name='PickupSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When this record was updated')),
                ('quantity', models.IntegerField(help_text='Quantidade a ser entregue do item de doação')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.pickup')),
                ('supply', models.ForeignKey(help_text='Item de doação a ser entregue', on_delete=django.db.models.deletion.PROTECT, to='inventory.supply')),
            ],
            options={
                'unique_together': {('pickup', 'supply')},
            },
        ),
    ]
