# Generated by Django 5.0 on 2024-05-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stock_options_alter_supply_options_and_more'),
        ('people', '0002_alter_beneficiary_options_alter_donor_options_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='donationsupply',
            options={'verbose_name': 'Donation Supply', 'verbose_name_plural': 'Donation Supplies'},
        ),
        migrations.AlterModelOptions(
            name='pickup',
            options={'verbose_name': 'Pickup', 'verbose_name_plural': 'Pickups'},
        ),
        migrations.AlterModelOptions(
            name='pickupsupply',
            options={'verbose_name': 'Pickup Supply', 'verbose_name_plural': 'Pickup Supplies'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(help_text='Who is donating', on_delete=django.db.models.deletion.PROTECT, to='people.donor', verbose_name='Donor'),
        ),
        migrations.AlterField(
            model_name='donationsupply',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of donated item to be received', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='donationsupply',
            name='supply',
            field=models.ForeignKey(help_text='Donated item to be received', on_delete=django.db.models.deletion.PROTECT, to='inventory.supply', verbose_name='Supply'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='beneficiary',
            field=models.ForeignKey(help_text='Donation recipient', on_delete=django.db.models.deletion.PROTECT, to='people.beneficiary', verbose_name='Beneficiary'),
        ),
        migrations.AlterField(
            model_name='pickupsupply',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of donated item to be delivered', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='pickupsupply',
            name='supply',
            field=models.ForeignKey(help_text='Donated item to be delivered', on_delete=django.db.models.deletion.PROTECT, to='inventory.supply', verbose_name='Supply'),
        ),
    ]
