# Generated by Django 5.0 on 2024-05-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_donation_options_alter_donationsupply_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', help_text='Approval Status', max_length=20),
        ),
    ]
