# Generated by Django 5.0 on 2024-05-16 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stock_options_alter_supply_options_and_more'),
        ('transactions', '0003_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsupply',
            name='stock_quantity',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='donationsupply',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.donation'),
        ),
        migrations.AlterField(
            model_name='donationsupply',
            name='supply',
            field=models.ForeignKey(help_text='Donated item to be received', on_delete=django.db.models.deletion.CASCADE, to='inventory.supply', verbose_name='Supply'),
        ),
    ]
