# Generated by Django 5.0 on 2024-05-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_donationsupply_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupsupply',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donationsupply',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pickupsupply',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of donated item to be received', verbose_name='Quantity'),
        ),
    ]
