# Generated by Django 5.0 on 2024-05-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When this record was updated')),
                ('name', models.CharField(help_text='Nome e sobrenome', max_length=80)),
                ('document', models.CharField(help_text='CPF ou CNPJ do doador', max_length=20, unique=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When this record was updated')),
                ('name', models.CharField(help_text='Nome e sobrenome ou Nome da empresa', max_length=80)),
                ('address_1', models.CharField(blank=True, help_text='Rua, número e complemento', max_length=255)),
                ('address_2', models.CharField(blank=True, help_text='Bairro e cidade', max_length=255)),
                ('email', models.CharField(blank=True, help_text='Email do doador', max_length=80, unique=True)),
                ('document', models.CharField(blank=True, help_text='CPF ou CNPJ do doador', max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
