# Generated by Django 5.0 on 2024-05-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name': 'Beneficiary', 'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name': 'Donor', 'verbose_name_plural': 'Donors'},
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='document',
            field=models.CharField(help_text="Beneficiary's CPF or CNPJ", max_length=20, unique=True, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='name',
            field=models.CharField(help_text="Beneficiary's full name", max_length=80, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='address_1',
            field=models.CharField(blank=True, help_text='Street address, including number and any additional details', max_length=255, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='address_2',
            field=models.CharField(blank=True, help_text='Neighborhood and city', max_length=255, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='document',
            field=models.CharField(blank=True, help_text="Donor's CPF or CNPJ", max_length=20, unique=True, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.CharField(blank=True, help_text='Email address of the donor', max_length=80, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(help_text="Donor's full name", max_length=80, verbose_name='Name'),
        ),
    ]
